version: '3.3'
services:
  web:
    build:
      context: ./
    volumes:
      - .:/src
    command: supervisor -e  'js,pug,html' index.js
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DB_CONTAINER=db
      - DB_PORT=3306
      - MYSQL_DATABASE=ridesharingapp
      - MYSQL_ROOT_USER=root
      - MYSQL_ROOT_PASSWORD=password
  db:
    image: mysql
    restart: always
    env_file:
      - ./.env
    ports:
      - "3308:3306"
    volumes:
      - ./db:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$$MYSQL_ROOT_PASSWORD"]
      interval: 10s
      timeout: 5s
      retries: 5
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    env_file:
      - ./.env
    ports:
      - "8081:80"
